### ISSUE TITLE
Pillow Conflict in requirements.txt

### ISSUE THREAD

**Issue by xorhex** [YoavLevi/IAT-Tracer#1]
Guessing one of these is suppose to be PIL?

```
Pillow==9.3.0
Pillow==10.3.0
```

**Comment by YoavLevi** [comment]
It's not supposed to be PIL. see
https://www.reddit.com/r/learnpython/comments/a2osgp/comment/eb08a2x/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

However, I've updated the file to eliminate the two conflicting requirements.
