### ISSUE TITLE
Provided EXE Throwing An Exception

### ISSUE THREAD

**Issue by xorhex** [YoavLevi/IAT-Tracer#2]
![Screenshot from 2024-07-10 13-28-04](https://github.com/YoavLevi/IAT-Tracer/assets/40742023/f0d6c35d-f568-47c6-a059-dda791c31196)
![Screenshot from 2024-07-10 13-30-11](https://github.com/YoavLevi/IAT-Tracer/assets/40742023/cd447f57-ee33-4c1a-ab1b-febee5e0d838)

**Comment by YoavLevi** [comment]
Thanks for your report!
Can you please specify the OS version you're trying to run the executable?

**Comment by xorhex** [comment]
![Screenshot from 2024-07-11 13-39-46](https://github.com/YoavLevi/IAT-Tracer/assets/40742023/2d073fc8-4e89-4907-961c-1d4b531ebe0a)

**Comment by YoavLevi** [comment]
I was looking into this issue and it seems like an incompatibility error of the Pyinstaller framework for older Windows versions.
It seems that for newer versions of Windows 10 it works correctly:
https://tria.ge/240712-npr1jatfka/behavioral2 (see replay monitor)
Whereas for older versions like yours, that same error occurs:
https://tria.ge/240712-npr1jatfka/behavioral1 (see replay monitor)

My suggestion is to do one of the following:
a. Update your Windows virtual machine version to Windows 10-2004 or Windows 11-21H2.
b. Run the Python script using an existing Python installation.
c. Recompile the script using Pyinstaller and the compilation command on your machine.

Let me know if any of that helped.
Yoav.

**Comment by xorhex** [comment]
Thanks for the feedback - it makes sense.  

I also tried running the python script but the setup process is not working due to conflicting libraries in the requirements.txt file

https://github.com/YoavLevi/IAT-Tracer/blob/main/requirements.txt
![image](https://github.com/user-attachments/assets/ea7643ee-6b01-47f5-b1b9-b7438be1afb4)

**Comment by YoavLevi** [comment]
I've just updated the [requirements.txt](https://github.com/YoavLevi/IAT-Tracer/blob/main/requirements.txt) file to eliminate the conflict. Now it should function correctly.

**Comment by xorhex** [comment]
Awesome, thank you!! :heart:
