### ISSUE TITLE
Python Version + Distutils

### ISSUE THREAD

**Issue by xorhex** [YoavLevi/IAT-Tracer#3]
What version of Python 3 is recommended?

I'm using Python 3.12.4 and it does not appear to like it.

```
File "C:\Users\User\AppData\Local \Programs\Python\Python312\Lib\site-packages\customtkinter\windows\ctk_tk.py", line 2, in <module>
from distutils.version import StrictVersion as Version
ModuleNotFoundError: No module named 'distutils'
```

Guessing due to this: https://docs.python.org/3.10/library/distutils.html#module-distutils

"[distutils](https://docs.python.org/3.10/library/distutils.html#module-distutils) is deprecated with removal planned for Python 3.12. See the [What’s New](https://docs.python.org/3.10/whatsnew/3.10.html#distutils-deprecated) entry for more information."

**Comment by xorhex** [comment]
Python 3.11.9 seems to work.

**Comment by YoavLevi** [comment]
As you said, the requirements file is intended to be used under Python 3.10/3.11. For Python 3.12, the distutils library should be replaced with setuptools for the tool to work correspondingly.
